config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  as :admin do
    get '/settings' => 'devise/registrations#edit', :as => 'admin_settings'
    put '/settings' => 'devise/registrations#update', :as => 'update_admin_settings'
  end
  namespace :api do
    resources :images, only: [:create]
  end
  resources :posts, path: "/blog"
  resources :todos do
    member do
      patch "done"
      patch "undo"
    end
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin
  validates :title, presence: { message: "Title can't be empty." }
  validates :content, presence: { message: "Content can't be empty." }
  default_scope { order(id: :desc) }
  extend FriendlyId
  friendly_id :date_and_title, use: :slugged

  def date_and_title
    date = created_at ? created_at.strftime("%Y %m %d") : Time.now.strftime("%Y %m %d")
    if title
        "#{date} #{title}"
    end
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def previous
    Post.where(["id < ?", id]).first
  end

  def next
    Post.where(["id > ?", id]).last
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
  scope :pending, -> { where(done: false) }
  scope :completed, -> { where(done: true).order(done_at: :desc) }
end

app/controllers/api/images_controller.rb
class Api::ImagesController < ApiController
  before_action :authenticate_admin!

	def create
		image = Cloudinary::Uploader.upload(params[:file])
		render json: {url: image["secure_url"]}
	end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.all
    @years = @posts.map {|post| post.created_at.year}.uniq
    @posts_archive = @posts.group_by {|post| [post.created_at.year, post.created_at.month]}
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted."
  end

  private
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :done, :undo]

  def index
    @todos = Todo.pending
    @completed_todos = Todo.completed
  end

  def new
    @todo = Todo.new
  end

  def create
    params[:descriptions].split("\r\n").each do |description|
      Todo.create(description: description)
    end
    redirect_to todos_path, notice: "To dos was successfully created."
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path, notice: "To do was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path, notice: "To do was successfully deleted."
  end

  def done
    @todo.update(done: true, done_at: DateTime.now)
    respond_to do |format|
      format.js
    end
  end

  def undo
    @todo.update(done: false, done_at: nil)
    respond_to do |format|
      format.js
    end
  end

  private
  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="grid-x grid-padding-x align-center">
    <div class="container">
      <div class="grid-x">
        <div class="small-6 cell">
          &copy; <%= Date.current.year%> Sean Yeoh
        </div>
        <div class="small-6 cell text-right">
          <a href="https://github.com/sean-yeoh" target="_blank">
            <i class="fa fa-github" aria-hidden="true"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_offcanvas_menu.html.erb
<ul class="vertical menu canvas-menu">
  <li>
    <a class="text-right" aria-label="Close menu" data-close>
      <i class="fa fa-times" aria-hidden="true"></i>
    </a>
  </li>
  <li><%= link_to "Home", root_path %></li>
  <% if admin_signed_in? %>
    <li><%= link_to "Todo List", todos_path %></li>
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to "Settings", admin_settings_path %></li>
    <li><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log In", new_admin_session_path %></li>
  <% end %>
</ul>

app/views/layouts/_topbar.html.erb
<header>
  <div class="grid-x grid-padding-x align-center">
    <div class="container">
      <div class="grid-x align-middle">
        <div class="small-4 cell">
          <button type="button" data-toggle="offCanvas">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
        </div>
        <div class="small-4 cell text-center">
          <%= link_to root_path do %>
            <%= image_tag "logo.png" %>
          <% end %>
        </div>
        <div class="small-4 cell text-right">
          <%= link_to new_post_path do %>
            <%= image_tag "new_post.svg", class: "new-post-link" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:url"           content="https://seanlovesan.herokuapp.com" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Our Blog" />
    <meta property="og:description"   content="This is my blog!" />
    <meta property="og:image"         content="https://cdn.pixabay.com/photo/2017/08/30/17/12/waffle-heart-2697904_960_720.jpg" />
    <title><%= content_for?(:title) ? yield(:title) : "Sean & Chui San's Blog" %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/topbar" %>
    <main>
      <div class="off-canvas-content" data-off-canvas-content>
        <div class="grid-x grid-padding-x align-center">
          <div class="container">
            <% flash.each do |key, msg| %>
              <div class="callout flash <%= key %>"><%= msg %></div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
    <div class="off-canvas position-left" id="offCanvas" data-off-canvas data-transition="overlap">
      <%= render "layouts/offcanvas_menu" %>
    </div>
  </body>
</html>

<script type="text/javascript">
  $(function(){
    $(document).foundation();
  })
</script>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { class: "post-form" } do |f| %>
  <%= f.input :title %>
  <%= f.input :content, label: "Content", as: :hidden, required: true %>
  <div id="scrolling-container">
  	<%= render "quill_toolbar" %>
	  <div id="editor-container">
	  	<%= @post&.content&.html_safe %>
		</div>
  </div>
  <%= f.button :submit, class: "expanded success" %>
<% end %>

<div class="loading" style="display: none;">
  <%= image_tag "loading.gif" %>
</div>

app/views/posts/_quill_toolbar.html.erb
<div id="toolbar">
  <select class="ql-font">
    <option value="serif"></option>
    <option value="monospace"></option>
    <option value="arial">Arial</option>
    <option value="helvetica">Helvetica</option>
  </select>
  <!-- Add font size dropdown -->
  <select class="ql-size">
    <option value="small"></option>
    <!-- Note a missing, thus falsy value, is used to reset to default -->
    <option selected></option>
    <option value="large"></option>
    <option value="huge"></option>
  </select>
  <select class="ql-color">
    <option selected="selected"></option><option value="#e60000"></option><option value="#ff9900"></option><option value="#ffff00"></option><option value="#008a00"></option><option value="#0066cc"></option><option value="#9933ff"></option><option value="#ffffff"></option><option value="#facccc"></option><option value="#ffebcc"></option><option value="#ffffcc"></option><option value="#cce8cc"></option><option value="#cce0f5"></option><option value="#ebd6ff"></option><option value="#bbbbbb"></option><option value="#f06666"></option><option value="#ffc266"></option><option value="#ffff66"></option><option value="#66b966"></option><option value="#66a3e0"></option><option value="#c285ff"></option><option value="#888888"></option><option value="#a10000"></option><option value="#b26b00"></option><option value="#b2b200"></option><option value="#006100"></option><option value="#0047b2"></option><option value="#6b24b2"></option><option value="#444444"></option><option value="#5c0000"></option><option value="#663d00"></option><option value="#666600"></option><option value="#003700"></option><option value="#002966"></option><option value="#3d1466"></option>
  </select>
  <select class="ql-background">
    <option selected="selected"></option><option value="#e60000"></option><option value="#ff9900"></option><option value="#ffff00"></option><option value="#008a00"></option><option value="#0066cc"></option><option value="#9933ff"></option><option value="#000000"></option><option value="#facccc"></option><option value="#ffebcc"></option><option value="#ffffcc"></option><option value="#cce8cc"></option><option value="#cce0f5"></option><option value="#ebd6ff"></option><option value="#bbbbbb"></option><option value="#f06666"></option><option value="#ffc266"></option><option value="#ffff66"></option><option value="#66b966"></option><option value="#66a3e0"></option><option value="#c285ff"></option><option value="#888888"></option><option value="#a10000"></option><option value="#b26b00"></option><option value="#b2b200"></option><option value="#006100"></option><option value="#0047b2"></option><option value="#6b24b2"></option><option value="#444444"></option><option value="#5c0000"></option><option value="#663d00"></option><option value="#666600"></option><option value="#003700"></option><option value="#002966"></option><option value="#3d1466"></option>
  </select>
  <button class="ql-bold" title="Bold"></button>
  <button class="ql-italic" title="Italic"></button>
  <button class="ql-underline" title="Underline"></button>
  <button class="ql-strike" title="Strikethrough"></button>
  <button class="ql-script" value="sub" title="Superscript"></button>
  <button class="ql-script" value="super" title="Subscript"></button>
  <button class="ql-list" value="ordered" title="Ordered List"></button>
  <button class="ql-list" value="bullet" title="Bullet List"></button>
  <button class="ql-blockquote" title="Blockquote"></button>
  <button class="ql-code-block" title="Code Block"></button>
  <button class="ql-align" value="" title="Align Left"></button>
  <button class="ql-align" value="center" title="Align Center"></button>
  <button class="ql-align" value="right" title="Align Right"></button>
  <button class="ql-align" value="justify" title="Align Justify"></button>
  <button class="ql-indent" value="-1" title="Indent Left"></button>
  <button class="ql-indent" value="+1" title="Indent Right"></button>
  <button class="ql-link" title="Link"></button>
  <button class="ql-image" title="Image"></button>
  <button class="ql-video" title="Video"></button>
  <button class="ql-clean" title="Clear"></button>
</div>

app/views/posts/edit.html.erb
<div class="grid-x align-middle">
  <div class="auto cell">
    <h2>Edit Post</h2>
  </div>
  <div class="shrink cell ">
    <%= link_to "Back", @post %>
  </div>
</div>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="grid-x grid-padding-x">
  <div class="cell large-8 small-order-2 large-order-1">
    <% @posts.each do |post| %>
      <div class="post">
        <h2 class="post-title"><%= link_to Gemojione.replace_unicode_moji_with_images(post.title), post_path(post) %></h2>
        <p class="subheader">Posted on <%= post.created_at.strftime("%A, %d %b %Y") %> by <%= post.admin.name %></p>
        <hr>
        <div class="post-content ql-editor">
          <%= Gemojione.replace_unicode_moji_with_images(post.content.html_safe) %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="cell large-4 small-order-1 large-order-2 archives">
    <h4 class="archives-header">Archives</h4>
    <ul class="vertical menu accordion-menu" data-accordion-menu>
      <% @years.each do |year| %>
        <li>
          <%= link_to year, "#" %>
          <ul class="menu vertical nested">
            <% @posts_archive.each do |yr_month, post_arr| %>
              <% if yr_month.first == year %>
                <li>
                  <%= link_to I18n.t("date.abbr_month_names")[yr_month.last], "#" %>
                  <ul class="menu vertical nested">
                    <% post_arr.each do |post| %>
                      <li><%= link_to "#{post.created_at.day} - #{post.title}", post_path(post), class: "archives-post-link" %></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
    <hr class="hide-for-large">
  </div>
</div>

app/views/posts/new.html.erb
<div class="grid-x align-middle">
  <div class="auto cell">
    <h2>New Post</h2>
  </div>
  <div class="shrink cell ">
    <%= link_to "Back", posts_path %>
  </div>
</div>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="grid-x align-middle">
  <div class="auto cell">
    <div class="grid-x align-middle">
      <div class="shrink cell actions">
        <%= link_to posts_path, class: "first" do %>
          <i class="fa fa-chevron-circle-left fa-lg" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="auto cell">
        <h2 class="post-title">
          <%= Gemojione.replace_unicode_moji_with_images(@post.title) %>
        </h2>
      </div>
    </div>
  </div>
  <% if admin_signed_in? %>
    <div class="shrink cell show-for-medium">
      <div class="actions">
        <%= link_to edit_post_path(@post), class: "edit-link first" do %>
          <i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>
        <% end %>
        <%= link_to @post, method: :delete, class: "delete-link last", data: { confirm: 'Are you sure?'}  do %>
          <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="grid-x align-middle">
  <div class="auto cell">
    <p class="subheader">Posted on <%= @post.created_at.strftime("%A, %d %b %Y") %> by <%= @post.admin.name %></p>
  </div>
  <div class="shrink cell show-for-medium">
    <% if @post.previous.nil? %>
      Prev
    <% else %>
      <%= link_to "Prev", @post.previous %>
    <% end %>
    |
    <% if @post.next.nil? %>
      Next
    <% else %>
      <%= link_to "Next", @post.next %>
    <% end %>
  </div>
</div>

<div class="show-for-small-only grid-x align-middle">
  <div class="small-6 cell text-left">
    <% if @post.previous.nil? %>
      Prev
    <% else %>
      <%= link_to "Prev", @post.previous %>
    <% end %>
    |
    <% if @post.next.nil? %>
      Next
    <% else %>
      <%= link_to "Next", @post.next %>
    <% end %>
  </div>
  <% if admin_signed_in? %>
    <div class="actions small-6 cell text-right">
      <%= link_to edit_post_path(@post), class: "edit-link first" do %>
        <i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>
      <% end %>
      <%= link_to @post, method: :delete, class: "delete-link last", data: { confirm: 'Are you sure?'}  do %>
        <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>
</div>

<hr>

<div class="post-content ql-editor">
  <%= Gemojione.replace_unicode_moji_with_images(@post.content.html_safe) %>
</div>

app/views/todos/_form.html.erb
<%= simple_form_for @todo do |f| %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/todos/done.js.erb
link_to_undo = "<a title='Undo' class='undo-link' data-remote='true' rel='nofollow' data-method='patch' href='/todos/<%= @todo.id %>/undo''> <i class='fa fa-undo' aria-hidden='true'></i></a>"
delete_link = "<a class='float-right delete-link' rel='nofollow' data-method='delete' href='/todos/<%= @todo.id %>'><i class='fa fa-trash fa-lg' aria-hidden='true'></i></a>"
$("#todo-<%= @todo.id%>").remove()
$(".completed-todos").prepend("<li id='todo-<%= @todo.id %>'>" + link_to_undo + " <span class='description'><%= @todo.description %></span>" + delete_link + "</li>")

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<div class="grid-x align-middle">
  <div class="auto cell">
    <h3>Pending To Dos</h3>
  </div>
  <div class="shrink cell ">
    <%= link_to "New Todo", new_todo_path, class: "button" %>
  </div>
</div>

<ul class="pending-todos">
	<% @todos.each do |todo| %>
		<li id="todo-<%= todo.id%>">
			<%= link_to [:done, todo], method: :patch, remote: true, title: "Done", class: "done-link" do %>
				<i class="fa fa-check" aria-hidden="true"></i>
			<% end %>
			<span class="description"><%= todo.description %></span>
			<%= link_to [todo], method: :delete, class: "float-right delete-link" do %>
			 	<i class="fa fa-trash fa-lg" aria-hidden="true"></i>
			<% end %>
		</li>
	<% end %>
</ul>

<br>

<h3>Completed</h3>
<ul class="completed-todos">
	<% @completed_todos.each do |todo| %>
		<li id="todo-<%= todo.id%>">
			<%= link_to [:undo, todo], method: :patch, remote: true, title: "Undo", class: "undo-link" do %>
				<i class="fa fa-undo" aria-hidden="true"></i>
			<% end %>
			<span class="description"><%= todo.description %></span>
			<%= link_to [todo], method: :delete, class: "float-right delete-link" do %>
			 	<i class="fa fa-trash fa-lg" aria-hidden="true"></i>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/todos/new.html.erb
<div class="grid-x align-middle">
  <div class="auto cell">
    <h2>Add Todos</h2>
  </div>
  <div class="shrink cell ">
    <%= link_to "Back", todos_path, class: "button" %>
  </div>
</div>

<%= simple_form_for @todo do |f| %>
  <%= text_area_tag :descriptions, nil, rows: 10 %>
  <%= f.button :submit, "Create To Dos", class: "expanded success" %>
<% end %>

app/views/todos/undo.js.erb
link_to_done = "<a title='Done' class='done-link' data-remote='true' rel='nofollow' data-method='patch' href='/todos/<%= @todo.id %>/done''> <i class='fa fa-check' aria-hidden='true'></i></a>"
delete_link = "<a class='float-right delete-link' rel='nofollow' data-method='delete' href='/todos/<%= @todo.id %>'><i class='fa fa-trash fa-lg' aria-hidden='true'></i></a>"
$("#todo-<%= @todo.id%>").remove()
$(".pending-todos").append("<li id='todo-<%= @todo.id %>'>" + link_to_done + " <span class='description'><%= @todo.description %></span>" + delete_link + "</li>")